[package]
name = "adafruit-bluefruit-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cortex-m = { version = "0.7", features = ["critical-section-single-core"]}
cortex-m-rtic = "1.1.3"

stm32f4xx-hal = { version = "0.13.2", features = ["stm32f401"] }

fugit = "0.3"

defmt = "0.3.2"
defmt-rtt = "0.4"

heapless = { version = "0.7", features = ["defmt-impl"] }
