[package]
name = "adafruit-bluefruit-protocol"
version = "0.1.0"
edition = "2021"

description = "A `no_std` parser for the Adafruit Bluefruit LE Connect controller protocol."
repository = "https://github.com/rursprung/adafruit-bluefruit-protocol-rs"
keywords = ["adafruit", "bluefruit", "protocol", "bluetooth", "embedded", "driver", "no_std"]
license = "MIT"

[dependencies]
defmt = { version = "0.3", optional = true }
heapless = { version = "0.7" }

[features]
defmt = ["dep:defmt", "heapless/defmt-impl"]
