[package]
name = "adafruit-bluefruit-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
defmt = { version = "0.3", optional = true }
heapless = { version = "0.7" }

[features]
defmt = ["dep:defmt", "heapless/defmt-impl"]
